services:
  gradio_app:
    build:
      context: .
      dockerfile: user_interface.Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./mobiBERT/data/data_store:/mobiBERT/data/data_store